#!/usr/bin/env bash
# Buat Pull Request secara manual (setelah di-approve oleh user)
# Usage: ./create-pr.sh [--base <branch>]
# Jalankan setelah branch di-push dan CI hijau

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

DEFAULT_BRANCH=$(detect_default_branch)
CURRENT_BRANCH=$(git branch --show-current)

echo "=== [jcode-workflow] Buat Pull Request ==="

# Validasi
if is_default_branch "${CURRENT_BRANCH}"; then
  echo "→ Sedang di default branch. Tidak perlu PR."
  exit 0
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "Error: GitHub CLI (gh) tidak ditemukan. Install gh dulu."
  exit 1
fi

# Cek apakah branch sudah di-push
if ! git ls-remote --exit-code origin "${CURRENT_BRANCH}" >/dev/null 2>&1; then
  echo "→ Branch ${CURRENT_BRANCH} belum di-push. Jalankan scripts/push.sh dulu."
  exit 1
fi

# Cek apakah PR sudah ada
EXISTING_PR=$(gh pr list --head "${CURRENT_BRANCH}" --json number --jq 'length' 2>/dev/null || echo "0")
if [ "${EXISTING_PR}" -gt 0 ]; then
  echo "→ PR sudah ada untuk branch ${CURRENT_BRANCH}. Skip."
  exit 0
fi

# Parse --base
BASE="${DEFAULT_BRANCH}"
if [ "${1:-}" = "--base" ] && [ -n "${2:-}" ]; then
  BASE="$2"
fi

# Buat PR
echo "→ Membuat PR ke base: ${BASE}"
TITLE=$(git log -1 --pretty=%s)
BODY="## Auto-generated by jcode workflow

- Branch: \`${CURRENT_BRANCH}\`
- Base: \`${BASE}\`
- Test status: hijau (gate passed)
- Conventional commit: ya

### Checklist
- [x] Characterization / unit / integration test hijau
- [x] Feature flag (jika applicable) default OFF
- [x] Tidak ada force-push ke default branch
"

gh pr create --title "${TITLE}" --body "${BODY}" --base "${BASE}"

echo "✓ PR berhasil dibuat untuk branch ${CURRENT_BRANCH} -> ${BASE}"
echo "  Review & merge via GitHub."
echo "=== [jcode-workflow] Selesai ==="
