#!/usr/bin/env bash
# Push branch saat ini + buat Pull Request otomatis (jika gh tersedia)
# Dipanggil setelah commit hijau

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

echo "=== [jcode-workflow] Push & buat PR ==="

DEFAULT_BRANCH=$(detect_default_branch)
CURRENT_BRANCH=$(git branch --show-current)

# Pastikan ada remote
if ! git remote get-url origin >/dev/null 2>&1; then
  echo "→ Tidak ada remote 'origin'. Skip push & PR."
  exit 0
fi

if is_default_branch "${CURRENT_BRANCH}"; then
  echo "→ Sedang di default branch (${DEFAULT_BRANCH}). Tidak membuat PR dari default branch."
  exit 0
fi

# Push
echo "→ Push branch ${CURRENT_BRANCH}..."
git push -u origin HEAD

# Buat PR jika GitHub CLI tersedia
if command -v gh >/dev/null 2>&1; then
  echo "→ Membuat Pull Request (base: ${DEFAULT_BRANCH})..."
  TITLE=$(git log -1 --pretty=%s)
  BODY="## Auto-generated by jcode workflow

- Branch: \`${CURRENT_BRANCH}\`
- Base: \`${DEFAULT_BRANCH}\`
- Test status: hijau (gate passed)
- Conventional commit: ya

### Checklist
- [x] Characterization / unit / integration test hijau
- [x] Feature flag (jika applicable) default OFF
- [x] Tidak ada force-push ke default branch
"

  gh pr create --title "${TITLE}" --body "${BODY}" --base "${DEFAULT_BRANCH}" \
    || echo "→ Gagal membuat PR (mungkin sudah ada atau tidak ada permission)."
else
  echo "→ GitHub CLI (gh) tidak ditemukan. Branch sudah di-push. Buat PR manual jika perlu."
fi

echo "=== [jcode-workflow] Selesai ==="
